{ config, pkgs, inputs, lib, ... }:

let
  # Read username from local config file (generated by bootstrap.sh)
  usernameFile = ../username.local;
  username = if builtins.pathExists usernameFile
    then lib.strings.trim (builtins.readFile usernameFile)
    else "admin";  # Fallback
in
{
  # Nix configuration
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      trusted-users = [ "@admin" username ];
    };
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # Homebrew configuration - installed but not restrictive
  nix-homebrew = {
    enable = true;
    enableRosetta = true;
    user = username;
    autoMigrate = true;
  };

  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = true;
      upgrade = true;
      # Don't use "uninstall" - allow users to install packages manually
      cleanup = "none";
    };
    # Declare any default brews/casks here
    brews = [];
    casks = [];
  };

  # System packages - basic shell tools
  environment.systemPackages = with pkgs; [
    # Core utilities
    git
    curl
    wget
    coreutils
    findutils
    gnugrep
    gnused
    gawk

    # Shell utilities
    tree
    htop
    jq
    ripgrep
    fd
    bat
    eza  # modern ls replacement
    fzf

    # Compression
    gzip
    unzip
    zip

    # Networking
    openssh
  ];

  # Zsh configuration with Oh My Zsh
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    enableBashCompletion = true;
    enableFzfCompletion = true;
    enableFzfHistory = true;
    enableSyntaxHighlighting = true;

    # Oh My Zsh configuration
    ohMyZsh = {
      enable = true;
      plugins = [
        "git"
        "sudo"
        "history"
        "direnv"
        "fzf"
      ];
      theme = "robbyrussell";
    };

    # Shell initialization
    interactiveShellInit = ''
      # Additional shell configuration
      export EDITOR="vim"
      export VISUAL="vim"

      # Better history
      export HISTSIZE=10000
      export SAVEHIST=10000

      # Aliases
      alias ll="eza -la"
      alias la="eza -a"
      alias l="eza"
      alias cat="bat --paging=never"
      alias grep="rg"
      alias find="fd"
    '';
  };

  # Set zsh as default shell
  environment.shells = [ pkgs.zsh ];

  # System defaults
  system = {
    # Used for backwards compatibility
    stateVersion = 5;

    defaults = {
      NSGlobalDomain = {
        AppleShowAllExtensions = true;
        AppleInterfaceStyle = "Dark";
        NSAutomaticCapitalizationEnabled = false;
        NSAutomaticSpellingCorrectionEnabled = false;
      };
      finder = {
        AppleShowAllExtensions = true;
        ShowPathbar = true;
        FXPreferredViewStyle = "Nlsv";
      };
      dock = {
        autohide = true;
        show-recents = false;
      };
    };
  };

  # Enable touch ID for sudo
  security.pam.enableSudoTouchIdAuth = true;
}
