{ config, pkgs, inputs, lib, ... }:

let
  # Read username from local config file (generated by bootstrap)
  # Check system location first, then local
  usernameFile =
    if builtins.pathExists /etc/nix-darwin/username.local
    then /etc/nix-darwin/username.local
    else ../username.local;
  username = if builtins.pathExists usernameFile
    then lib.strings.trim (builtins.readFile usernameFile)
    else "admin";  # Fallback
in
{
  # Let Determinate Nix installer manage Nix (don't conflict with nix-darwin)
  nix.enable = false;

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # Homebrew configuration - installed but not restrictive
  nix-homebrew = {
    enable = true;
    enableRosetta = true;
    user = username;
    autoMigrate = true;
  };

  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = true;
      upgrade = true;
      # Don't use "uninstall" - allow users to install packages manually
      cleanup = "none";
    };
    # Declare any default brews/casks here
    brews = [];
    casks = [];
  };

  # System packages - basic shell tools
  environment.systemPackages = with pkgs; [
    # Core utilities
    git
    curl
    wget
    coreutils
    findutils
    gnugrep
    gnused
    gawk

    # Shell utilities
    tree
    htop
    jq
    ripgrep
    fd
    bat
    eza
    fzf

    # Compression
    gzip
    unzip
    zip

    # Networking
    openssh
  ];

  # Zsh configuration
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    enableBashCompletion = true;
    enableFzfCompletion = true;
    enableFzfHistory = true;
    enableSyntaxHighlighting = true;

    interactiveShellInit = ''
      export EDITOR="vim"
      export VISUAL="vim"
      export HISTSIZE=10000
      export SAVEHIST=10000

      alias ll="eza -la"
      alias la="eza -a"
      alias l="eza"
    '';
  };

  # Set zsh as default shell
  environment.shells = [ pkgs.zsh ];

  # System defaults
  system = {
    # Used for backwards compatibility
    stateVersion = 5;

    defaults = {
      NSGlobalDomain = {
        AppleShowAllExtensions = true;
        AppleInterfaceStyle = "Dark";
        NSAutomaticCapitalizationEnabled = false;
        NSAutomaticSpellingCorrectionEnabled = false;
      };
      finder = {
        AppleShowAllExtensions = true;
        ShowPathbar = true;
        FXPreferredViewStyle = "Nlsv";
      };
      dock = {
        autohide = true;
        show-recents = false;
      };
    };
  };

  # Set primary user for user-specific options (homebrew, system defaults, etc.)
  system.primaryUser = username;
}
