{ config, pkgs, lib, ... }:

let
  # Read hostname from local config file (generated by bootstrap)
  # Check system location first, then local
  hostnameFile =
    if builtins.pathExists /etc/nix-darwin/hostname.local
    then /etc/nix-darwin/hostname.local
    else ../hostname.local;
  hostname = if builtins.pathExists hostnameFile
    then lib.strings.trim (builtins.readFile hostnameFile)
    else "mini-default";
in
{
  # Set hostname to mini-${serial_number}
  networking = {
    hostName = hostname;
    computerName = hostname;
    localHostName = hostname;
  };

}
