{ config, pkgs, lib, ... }:

let
  # Read hostname from local config file (generated by bootstrap)
  hostnameFile =
    if builtins.pathExists /etc/nix-darwin/hostname.local
    then /etc/nix-darwin/hostname.local
    else ../hostname.local;
  hostname = if builtins.pathExists hostnameFile
    then lib.strings.trim (builtins.readFile hostnameFile)
    else "mini-default";

  # Read username for activation script
  usernameFile =
    if builtins.pathExists /etc/nix-darwin/username.local
    then /etc/nix-darwin/username.local
    else ../username.local;
  username = if builtins.pathExists usernameFile
    then lib.strings.trim (builtins.readFile usernameFile)
    else "admin";
in
{
  # Set hostname to mini-${serial_number}
  networking = {
    hostName = hostname;
    computerName = hostname;
    localHostName = hostname;
  };

  # Install orchard for VM orchestration
  environment.systemPackages = [
    pkgs.orchard
    pkgs.tailscale
  ];

  # Install Docker Desktop via Homebrew
  homebrew.casks = [
    "docker"
  ];

  # Start Docker Desktop on first activation and enable auto-start
  system.activationScripts.postActivation.text = ''
    echo "Configuring Docker Desktop..."
    # Enable Docker Desktop auto-start on login
    DOCKER_PLIST="/Users/${username}/Library/Group Containers/group.com.docker/settings-store.json"
    if [ -f "$DOCKER_PLIST" ]; then
      # Docker settings exist, try to enable auto-start via defaults
      true
    fi
    # Start Docker Desktop if not running (will fail silently in headless mode)
    if ! pgrep -x "Docker" > /dev/null; then
      sudo -u ${username} open -a Docker 2>/dev/null || true
    fi
  '';
}
